Bitcoin processor
serai-dex/serai pull request #232
Opened 2023-01-16 04:20 UTC by vrx00

I completed and tested most of the part for bitcoin processor. I will keep improving it.

2023-01-16 17:31 UTC, kayabaNerve requested changes
I only got through to the RPC and will review the rest later.

The RPC needs to be slashed and burned. Not only are several functions unusable to us provided, yet several inefficient/worse functions are provided when the optimal ones are right there. I've called out several functions for removal. That file should be rewritten as cleanly and minimally as possible. Only functions we are using or explicitly plan to use.

A lot of this is extremely basic. I'd imagine it take 30-60m to work through this as it's generally formatting/misc comments. Just needs to be cleaned up.

Happy to see the PR. Will finish review later.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/Cargo.toml
> +[package]
This shouldn't exist. `coins/` is a folder, not a crate.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +edition = "2021"
Missing description, license (same as `coins/ethereum`, AGPL-3.0-only), and a copy of the AGPL short text as `LICENSE` (see `coins/ethereum` for an instance), repository, and authors.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +zeroize = { version = "1.5", features = ["zeroize_derive"] }
Missing new line.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +bitcoin = {version = "0.29.2", features=["serde"]}
Missing spaces, don't specify patch on this nor the package above it.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +serde = {version = "1.0", features = ["derive"]}
Missing spaces on {}.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +sha2 = { version = "0.10" }
Unnecessary object since it's just the version field.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +frost = { version= "0.5", package = "modular-frost", path = "../../crypto/frost", features = ["secp256k1"] }
Missing space on `version=`.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +dleq = {  version = "0.2", package = "dleq", path = "../../crypto/dleq", features = ["serialize"]}
Extra space before version, unnecessary package name specification.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +publish = false
We likely do want to publish this as we do `coins/monero`, just to offer FROST utils around `bitcoin`. I'd like to keep this AGPL-3.0-only/`publish = false` for now yet come back to that.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +secp256k1 = {version = "0.24.1", features = ["global-context", "rand-std"] }
Don't specify the patch version. cargo will grab the latest applicable subversion. Specifying `.1` as a subversion prevents us from using the latest subversion of `0.24`, missing bug fixes, and also adding two distinct versions of this crate to our depends.

Also, missing space before `version`.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +anyhow = "1.0.32"
What's the justification for anyhow? `coins/ethereum` added some error thing because `ethers-rs` used it, so it was effectively required to. anyhow is generally intended for binaries though, so I'm unsure why it's here.

Also, don't specify the patch version.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +log = "0.4.8"
Don't specify patch.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +bitcoincore-rpc-json = "0.16.0"
Don't specify patch on either of the above two packages.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +    data.update(&m[..]);
This should be able to just be `m`.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +    let tag = b"BIP0340/challenge";
Should be a constant.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +    let tag_hash = Sha256::digest(tag);
We can use a lazy_static for this so it's only calculated once. https://github.com/serai-dex/serai/blob/develop/coins/monero/src/lib.rs#L88-L90 for an example.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +    data.update(a_encoded_point.x().to_owned().unwrap());
I'm unsure if these to_owned are needed, as this returns a reference the Digest trait should be able to handle. If it doesn't, I *think* `.unwrap().as_ref()` will work without explicitly copying it.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +pub fn taproot_key_spend_signature_hash(
Ideally, this wouldn't be public. It should be internal to `coins/bitcoin` which just exposes the FROST API over PSTs.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +  if input_index >= psbt.inputs.len() || input_index >= psbt.unsigned_tx.input.len() {
Right now, this is public, so this is needed since it looks like pbst unfortunately doesn't guarantee its consistency.

If we make this non-public, we only need to run this check whenever we create the machine and take ownership of the PBST. Then, since we guaranteed consistency at the start, and no longer expose a mutation API, we won't need such checks.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +    .map_err(|_| SignerError::InvalidSighash)?;
This will accept any sighash defined here: https://docs.rs/bitcoin/latest/bitcoin/util/sighash/enum.SchnorrSighashType.html

Do we consider this a safety issue?

Serai itself should solely use All, and explicitly use All. `coins/bitcoin`, if we want to publish it to offer a Rust lib for FROST BTC TXs, shouldn't be so opinionated. It also isn't an issue for Serai since we aren't sending PBSTs over the wire, letting a malicious node instead use None to steal funds. We'll independently create TXs using All.

I just wanted to get your comment. This does seem to be fitting for `coins/bitcoin`.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +  let witness_utxos = (0..psbt.inputs.len()).map(|i| psbt.get_utxo_for(i)).collect::<Vec<_>>();
filter_map here and it'll automatically exclude None, voiding the need for all_witness_utxos and the following if statement.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +    sighash::Prevouts::All(&all_witness_utxos)
This hard-codes to All despite explicitly supporting any sighash type above. This should either use the prior-defined type or we should explicitly only support `All` right now. We shouldn't have halfway code which introduces the potential for inconsistencies. I'm not asking to support all variants, I couldn't care less right now, just to be consistent in what we support.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +  Ok((hash.unwrap(), sighash_type))
This shouldn't unwrap since it works off unvalidated input.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +use std::{collections::HashMap, fmt::Debug, vec::Vec, str::FromStr};
Unnecessary brackets on serde, and unnecessary import of Vec which is auto-imported.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    hashes::hex::FromHex, secp256k1::ecdsa::Signature, Address, Amount, EcdsaSighashType, OutPoint,
This file has a 4-space indent?

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +use crate::rpc_helper::{
Should this just use `rpc_helper::*`?

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +use bitcoincore_rpc_json::{
Also, should this just use `*`?

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub fn new(url: String, username: String, userpass: String) -> anyhow::Result<Rpc> {
This doesn't accept an URL. It accepts an IP address or domain. We then create an http URL out of it.

Rename the variable to IP? Take in a single URL string which is expected to be pre-formatted? Then it also supports un-authed RPC/RPC over https without further edits, and you don't have to craft a URL.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +            None => Ok(parsed_res.result.unwrap()),
I'm unsure this unwrap is safe. Right now, a node can return no error yet no result, causing a panic. I'm unsure if an honest BTC node will but...

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +        let info: usize = self.rpc_call::<usize>("getblockcount", &[]).await?;
This specifies `info: usize` yet also `rpc_call::<usize>`. Only one should be needed.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_height(&self) -> anyhow::Result<usize> {
Could we call this `get_latest_block_number`, please? Assuming that whatever this returns is always a valid block number on the chain it's describing.

Also, in general, we should have our APIs be get_latest_block_hash and get_block_number(hash). It ensures determinism. This function does still have value, I just wanted to leave that comment.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_block_info(&self, block_hash: &str) -> anyhow::Result<GetBlockResult> {
Remove, since we only use it to get the block number and I'd like to minimize this file please.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_block_index(&self, block_hash: &str) -> anyhow::Result<usize> {
get_block_number

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_block_with_transactions(&self, block_hash: &bitcoin::BlockHash) -> anyhow::Result<GetBlockWithDetailResult> {
What's the difference between this and `get_block`? Shouldn't the block always have its TXs, from a design perspective? Else, it's effectively just the header.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_spendable(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_o_indexes(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn lock_unspent(&self, outputs: &[OutPoint]) -> Result<bool> {
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn unlock_unspent(&self, outputs: &[OutPoint]) -> Result<bool> {
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_fee_per_byte(&self, conf_target: Option<usize>) -> anyhow::Result<u64> {
Remove. While `estimatesmartfee` appears deterministic, that assumes a consistent best block which we can't guarantee, both due to competitors and due to latency.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_transactions(
Remove get_transaction and get_transactions for functions (such as the following get_raw_transactions) supporting `bitcoin`'s Transaction, a usable and portable type.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_raw_transactions(
Just call get_transactions.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn is_confirmed(&self, tx_hash: &str) -> anyhow::Result<bool> {
Remove. While this is suitably deterministic, it hardcodes the confirmation count to 10. The scanner won't need this and I'd rather not support this.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_transaction_block_number(&self, tx_hash: &str) -> anyhow::Result<usize> {
Is this needed? If not, please remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_block_transactions(
Remove as it's not using `bitcoin::Transaction`.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_block_raw_transactions(
Why do we have get_raw_transaction, get_block_raw_transactions, get_block, get_block_with_transactions, AND get_raw_transactions? Can we *please* just consolidate these.

The processor expects/supports either:
- Block with TXs
- Block without TXs

The former is superior and overall more efficient. The only reason we support the latter is for a Monero consideration/API boundary. Can we just have `get_block`, returning a bitcoin type with all its TXs, please? If we technically need to define a block as a block hash, and from there have get_block_transactions, fine, I just want to minimize this file.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_raw_transaction_hex(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_raw_transaction_info(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn create_raw_transaction(
Remove this and its hex variant, please.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn fund_raw_transaction<R: RawTx>(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn sign_raw_transaction<R: RawTx>(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn sign_raw_transaction_with_wallet<R: RawTx>(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn sign_raw_transaction_with_key<R: RawTx>(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn send_raw_transaction<R: RawTx>(&self, tx: R) -> Result<bitcoin::Txid>
Should RawTx be a generic?

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn send_raw_str_transaction(&self, raw_tx: String) -> Result<bitcoin::Txid>
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn verify_message(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_new_address(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn generate_to_address(&self, nblocks: usize, address: &str) -> Result<Vec<String>> {
Label test.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn get_balance(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn decode_raw_transaction<R: RawTx>(&self, tx: R) -> Result<GetBlockResult>
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn list_transactions(
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc.rs
> +    pub async fn test_mempool_accept<R: RawTx>(
Do we need this beyond? What does it offer sendraw doesn't?

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +pub struct GetBlockWithDetailResult {
Remove.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +pub struct RpcResponse<T> {
I believe if this is written as an enum, we can ensure it's either result or error, not both, resolving a prior comment.

Should support Clone.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +#[derive(Serialize)]
Why does this have a lifetime? Have it either take static strings or String.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +pub enum RpcError {
Derive Clone, PartialEq, Eq.

Use thiserror.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +impl fmt::Display for RpcError {
Not needed with thiserror.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +impl error::Error for RpcError {
Not needed with thiserror.

2023-01-16 17:31 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +pub trait RawTx: Sized + Clone {
Can we just support Transaction and Transaction alone?

2023-01-16 22:02 UTC, kayabaNerve requested changes

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/rpc_helper.rs
> +pub fn opt_into_json<T>(opt: Option<T>) -> Result<serde_json::Value>
These functions shouldn't be `pub`. Additionally, I think serde_json already converts None to null.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +    sighash::{SchnorrSighashType},
Unnecessary {}s.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +  curve::{Secp256k1},
{}

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +use rand_core::{RngCore};
{}

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +use core::{fmt::Debug};
{}

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +    height: usize,
Let's try not use "height" as it's ambiguous between currencies. This should be the latest block's "number".

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +      let txid: [u8; 32] = input.previous_output.txid.to_vec()[0..32].try_into().unwrap();
Is the TX ID ever not 32 bytes? If it's 32 bytes, you can don't need the `[.. 32]`. Also, you shouldn't need the .to_vec here.

(so ideally just `input.previous_output.txid.try_into().unwrap()`, yet you may need `input.previous_output.txid.as_ref().try_into().unwrap()`)

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +        b"input_shared_key",
"shared_key"? The following variable is "internal_key". I'm unsure what the terminology is here.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +      sigs.push(AlgorithmMachine::new(algorithm.clone(), keys.clone()).unwrap());
We have to tweak the keys to be even, and then further tweak per-input, right? The 'key path'? Shouldn't that occur here?

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +      transcript.append_message(b"payment_address", payment.script_pubkey.as_bytes());
Payment is intended to be (Address, amount). It's perfectly fine to transcript `output_script` and `output_amount` here though. This doesn't need to operate off "payments", which is a universal format.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +    total_weight += (address.script_pubkey().to_hex().len()/2) * 1 * 4;
as_bytes, don't use hex

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +  pub fn calculate_weight(total_inputs: usize, address: &bitcoin::Address, change: bool) -> usize{
Can't we use a function from `bitcoin` OR calculate via `.serialize().len()`? I understand the latter is faulty regarding Segwit weight, but it'd be better to get the base cost than this.

Also, why does this take a single address out?

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +    let mut msg_list = Vec::new();
We should calculate this at time of use, not here.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +        let (sig, share) = sig.sign(commitments.remove(0), &msg_list.remove(index))?;
This iterates indexes 0 to n, yet calls remove. This either needs to remove 0, like commitments, or not remove from the list yet just calculate the msg here. Right now, for two inputs, it'll remove 0, be left with what was 1 at position 0, then try to remove 1, failing as nothing is currently at 1.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +impl SignatureMachine<PartiallySignedTransaction> for TransactionSignatureMachine {
This should return a Transaction, not a PBST.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/transactions.rs
> +    self.sigs.iter().map(|clsag| clsag.read_share(reader)).collect()
"clsag"

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/wallet.rs
> +use bitcoin::{Txid};
{}

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/wallet.rs
> +    res.extend(self.amount.to_le_bytes().to_vec());
Don't use to_vec just to extend off it. If the raw bytes don't work, just borrow with `&`.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/tests/signature.rs
> +  let mut _sig = sign(
Don't use `_sig` for a used variable. Use `sig`.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/tests/signature.rs
> +  _sig.s += Scalar::from(_offset);
Ideally, we'd have a BitcoinSchnorr Algorithm to handle this for us.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/tests/signature.rs
> +  let _res = sig.verify(&msg, &pubkey).unwrap();
Don't assign `_res`. `.unwrap()` is sufficient to handle the result.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +k256 = { version = "0.11", features = ["arithmetic", "keccak256", "ecdsa"] }
Don't add keccak nor ecdsa if not needed? Neither should be?

2023-01-16 22:02 UTC, kayabaNerve commented on processor/Cargo.toml
> +k256 = { version = "0.11", features = ["arithmetic", "keccak256", "ecdsa"] }
Same comment on keccak/ecdsa features.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/Cargo.toml
> +sha2 = { version = "0.10" }
Unnecessary object.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/Cargo.toml
> +serde_json = "1.0"
Please correct spacing and remove patch version specification.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +use transcript::{RecommendedTranscript};
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  curve::{Secp256k1},
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  Block as MBlock,
BBlock

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  Txid, schnorr::{TweakedPublicKey},
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  crypto::{make_even},
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  wallet::{SpendableOutput},
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  transactions::{TransactionMachine, SignableTransaction as MSignableTransaction},
BSignable

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/wallet.rs
> +  pub txid: Txid,//[u8;32],
This can be a Txid. It doesn't have to be a [u8; 32].

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/wallet.rs
> +pub struct SpendableOutput {
Can we not just wrap a bitcoin type for these fields? Like Vout? And use its ser/deser?

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  elliptic_curve::{
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  pub mask: u64,
Bitcoin doesn't have a mask

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    Bitcoin { rpc: Rpc::new(url, username.unwrap(), userpass.unwrap()).unwrap()}
Should we just use a pre-formatted URL string?

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let ret: [u8; 36] = serialized_data[0..36].try_into().unwrap();
This is dependent on a different crate's serialization format. Please redo the serialization for TX hash/vout index here.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  type Transaction = PartiallySignedTransaction;
This isn't correct. It should be bitcoin::Transaction.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let mblock = Block(info.block_hash().to_vec()[0..32].try_into().unwrap(),info);
You shouldn't need to_vec here.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +        if output_tx.script_pub_key.script().unwrap().cmp(&main_addr.script_pubkey()).is_eq() {
You should just be able to use `==`

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/wallet.rs
> +pub struct SpendableOutput {
OutPoint specifically could merge these top two fields.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let ret: [u8; 36] = serialized_data[0..36].try_into().unwrap();
Moving to Outpoint would potentially help here.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let transaction_weight = MSignableTransaction::calculate_weight(vin_alt_list.len(), &payments[0].0, false);
This only uses a single payment to calculate weight.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +      return Err(CoinError::ConnectionError);
We should have an error in Coin, `NotEnoughFunds`. Sorry it wasn't already there.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +      if target_sat < input_sat {
This is incomplete. Bitcoin won't relay outputs worth less than it costs to spend them. I think the formula we want to use is *something* like `target_sat < (input_sat - (fee.calculate(calculate_weight(&[vin[0], &[payments[0]], false) * 2))`. Say the remaining change has to be able to fund 2x the fees for a 1:1 TX.

Additionally, at some point, we need to drop outputs worth less than that...

Feel free to mark this TODO. Just needs to be documented.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    assert!(key.to_encoded_point(true).tag() == Tag::CompressedEvenY, "YKey is odd");
debug_assert

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +      psbt.inputs[i].tap_internal_key = Some(xonly_pubkey);
Isn't the internal key supposed to tweaked per the key path? If this passes tests, it passes tests, but https://bitcoin.stackexchange.com/questions/110402/how-to-tweak-a-public-key-for-taproot says it shouldn't AFAICT. Feel free to comment if you know more.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    return Ok(SignableTransaction { keys: keys, transcript: transcript, height: block_number+1, actual: MSignableTransaction{tx: psbt, fee:actual_fee} });
Can we please not use height here? I'm pretty sure Bitcoin treats height as the latest block number, making this incorrect.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let s_raw_transaction = self.rpc.send_raw_str_transaction(target_tx.raw_hex()).await.unwrap();
Why is this in hex? There should be a bytes option.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  ) -> Result<(Vec<u8>, Vec<<Self::Output as OutputTrait>::Id>), CoinError> {
Coin shouldn't return Output IDs. You matched Monero here, and the API Coin defined, yet as I'm reading this, it makes no sense.... I can edit develop or you're welcome to add it to this PR.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +          txid: Txid::from_str(target_tx.txid().to_string().as_str()).unwrap(),
You get a TX ID, convert it to a string, just to deserialize it from a string.
`target_tx.txid()`

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  fn tweak_keys<'a>(&self, key: &'a mut ThresholdKeys<Self::Curve>) {
This shouldn't need a lifetime.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    use bitcoincore_rpc_json::{AddressType};
{}

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let new_addr = self.rpc.get_new_address(None, Some(AddressType::Bech32)).await.unwrap();
Can't we just generate a garbage address using the bitcoin lib so we can purge reliance on the often-changing bitcoin wallet RPC?

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +  async fn test_send(&self, address: Self::Address) {
On the one hand, I'm fascinated by this using FROST itself. On the other hand, this should just send a small amount of funds to the provided address. Just generate a P2PKH with `bitcoin` you receive to (using `gen_to_addr`), and send from there. That way, if scanning breaks, we don't need to wonder if test_send messed up or if scanning did.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/mod.rs
> +
Random new line?

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/monero.rs
> +use std::collections::HashMap;
Not needed import.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/mod.rs
> +  fn tweak_keys<'a>(&self, key: &'a mut ThresholdKeys<Self::Curve>);
Shouldn't need lifetime.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/tests/mod.rs
> +  coin.mine_block().await;
I think these three lines are old code, no longer relevant.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/tests/mod.rs
> +      .prepare_sends(1, vec![(wallet.address(), 4999900000)], fee)
100000000? Keep it round?

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/tests/mod.rs
> +      break;
This shouldn't break here. That invalidates this test by silently returning if it fails.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/wallet.rs
> +        self.coin.tweak_keys(keys);
Except for this one line, I don't believe any lines here are actually needed. `git checkout -f processor/src/wallet.rs`?

We should tweak keys at time of addition to self.keys so we only tweak them once.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +      psbt.inputs[i].tap_internal_key = Some(xonly_pubkey);
I have no idea how this passes, if it does. Congrats if so, not like I care to complain it works... Would still love to know why.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +          vout: i as u32,
Please use the explicit `u32::try_from(i).unwrap()`.

2023-01-16 22:02 UTC, kayabaNerve commented on coins/bitcoin/src/crypto.rs
> +        Some(in_tx.output[tx.input[input_index].previous_output.vout as usize].clone())
Please use the explicit `usize::try_from(tx.input[input_index].previous_output.vout).unwrap()`.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +      Ok(val) => Ok(val as usize),
Please use explicit casts here, if needed. This RPC function should just return usize from the get go...

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let block_number = match block_result {
Use `?` on the prior line so you don't have to match here.

2023-01-16 22:02 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +      psbt.inputs[i].sighash_type = Some(PsbtSighashType::from_u32(SchnorrSighashType::All as u32));
Explicit casts. For the latter, `SchnorrSighashType::All.into()` should work. Else, `PsbtSighashType::from(SchnorrSighashType::All)` definitely will.

2023-01-16 22:04 UTC, kayabaNerve commented
Finished the review. A lot of these comments are duplicates/brief. We can also make some topics, like a BitcoinSchnorr algorithm, fee code, etc TODOs. It's just important to start getting things tracked.

Please merge develop in and run `cargo +nightly fmt` to get things started. Then I'd resolve clippy (also nightly), then start making changes.

2023-01-16 22:05 UTC, kayabaNerve commented
If clippy complains about elliptic curve variables being upper case, add `#[allow(clippy::non_snake_case)]` or whatever the label is to the line in question.

2023-01-17 00:29 UTC, vrx00 commented on coins/bitcoin/Cargo.toml
> +zeroize = { version = "1.5", features = ["zeroize_derive"] }
added new line

2023-01-17 00:33 UTC, vrx00 commented on coins/bitcoin/Cargo.toml
> +publish = false
Makes sense. For now, I am keeping it as it is then.

2023-01-17 00:48 UTC, vrx00 commented on coins/bitcoin/src/rpc.rs
> +    hashes::hex::FromHex, secp256k1::ecdsa::Signature, Address, Amount, EcdsaSighashType, OutPoint,
changed it to 2-space indent

2023-01-23 02:04 UTC, kayabaNerve reviewed
Few misc items I noted. Didn't do a full re-review.

2023-01-23 02:04 UTC, kayabaNerve commented on coins/bitcoin/Cargo.toml
> +lazy_static = "1"
Missing newline.

2023-01-23 02:04 UTC, kayabaNerve commented on coins/bitcoin/src/lib.rs
> +pub mod json_helper;
Missing newline.

2023-01-23 02:04 UTC, kayabaNerve commented on coins/bitcoin/src/json_helper.rs
> +pub trait RawTx: Sized + Clone {
Why keep this around? We only have `Transaction` now, as we should.

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    self.rpc.generate_to_address(1, new_addr.to_string().as_str()).await.unwrap();
You can use `&` to get a `&str`. `as_str()` isn't needed. (`&new_addr.to_string()`)

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let main_addr = Address::p2wpkh(&public_key, Network::Regtest).unwrap();
Create a dedicated test function to get a random key/address?

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    self.rpc.generate_to_address(1, main_addr.to_string().as_str()).await.unwrap();
Create a dedicated test function to get an unlocked coinbase output?

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let script_code = Address::p2pkh(&public_key, Network::Testnet).script_pubkey();
Why Testnet when the rest used Regtest?

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    let _result = self.rpc.send_raw_transaction(&new_transaction).await.unwrap();
`let _result =` shouldn't be needed.

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    new_transaction.input[0].witness = signed_witness;
This *could* be simplified by using P2PKH. I don't care to ask you to move to an inferior format, from a working piece of code, in the name of simplicity, yet I did want to note the thought.

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/mod.rs
> +use std::{marker::Send,collections::HashMap};
Should no longer be necessary.

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/tests/mod.rs
> +  if futures.len() > 0 {
This if shouldn't exist. There should always be a future.

It also somewhat-voids the test.

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +    self.0
self.0.block_hash()

2023-01-23 02:04 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +pub struct Block([u8; 32], BBlock);
You don't need the `[u8; 32]` since you can get the hash from the block itself.

2023-01-23 04:42 UTC, kayabaNerve commented on processor/src/coin/bitcoin.rs
> +pub struct Block([u8; 32], BBlock);
Actually, you shouldn't even need the tuple. You should be able to implement BlockTrait directly on Block.

2023-01-31 12:48 UTC, merged